//! `ExecutorServer` — rmcp 1.5 ServerHandler with `#[tool_handler]`.
//!
//! Plan 03 will extend this `impl ServerHandler` block with `#[prompt_handler]`
//! plus the 2 Phase 1 prompts (`write_evm_strategy`, `review_evm_strategy`).
//! Per Pitfall 6 the two macros MUST share one impl block, which is why we set
//! up `prompt_router` now and leave space for Plan 03 to add prompt methods.

use rmcp::{
    ServerHandler,
    handler::server::router::{prompt::PromptRouter, tool::ToolRouter},
    model::{ServerCapabilities, ServerInfo},
    tool_handler,
};

#[derive(Clone)]
pub struct ExecutorServer {
    pub(crate) tool_router: ToolRouter<Self>,
    // Plan 03 wires `#[prompt_handler(router = self.prompt_router)]`, which will
    // start reading this field. Until then the empty router is stored so the
    // struct shape is stable across plans (no API churn when prompts land).
    #[allow(dead_code)]
    pub(crate) prompt_router: PromptRouter<Self>,
}

impl ExecutorServer {
    pub fn new() -> Self {
        Self {
            // `Self::tool_router()` is generated by `#[tool_router]` in tools.rs.
            tool_router: Self::tool_router(),
            // Empty router today; Plan 03 replaces this with `Self::prompt_router()`
            // once a `#[prompt_router] impl ExecutorServer { ... }` block exists.
            prompt_router: PromptRouter::new(),
        }
    }
}

impl Default for ExecutorServer {
    fn default() -> Self {
        Self::new()
    }
}

// NOTE: Plan 03 will add `#[prompt_handler(router = self.prompt_router)]` to this
// same impl block (Pitfall 6: tool_handler and prompt_handler must coexist).
#[tool_handler(router = self.tool_router)]
impl ServerHandler for ExecutorServer {
    fn get_info(&self) -> ServerInfo {
        let caps = ServerCapabilities::builder()
            .enable_tools()
            .enable_prompts()
            .enable_resources()
            .build();
        ServerInfo::new(caps).with_instructions(
            "Onchain Strategy MCP — v1 runtime surface. \
             Write-capable tools (strategy_register, strategy_delete, strategy_run_once, \
             policy_update) return a structured `unimplemented` error (JSON-RPC code -32010, \
             data.code=\"unimplemented\", data.phase=<N>) until their phase lands.",
        )
    }
}
