//! `ExecutorServer` — rmcp 1.5 `ServerHandler` with `#[tool_handler]` +
//! `#[prompt_handler]` on a single `impl ServerHandler` block (Pitfall 6),
//! plus hand-written `list_resources` / `list_resource_templates` /
//! `read_resource` overrides delegating to `crate::resources`.
//!
//! - Tools: macro-generated by `#[tool_router]` in `tools.rs`.
//! - Prompts: macro-generated by `#[prompt_router]` in `prompts.rs`.
//! - Resources: hand-written below (Phase 1 returns empty list + 3 URI
//!   templates + always-`resource_not_found` read).

use rmcp::{
    ErrorData as McpError, RoleServer, ServerHandler,
    handler::server::router::{prompt::PromptRouter, tool::ToolRouter},
    model::{
        GetPromptRequestParams, GetPromptResult, ListPromptsResult, ListResourceTemplatesResult,
        ListResourcesResult, PaginatedRequestParams, ReadResourceRequestParams,
        ReadResourceResult, ServerCapabilities, ServerInfo,
    },
    prompt_handler,
    service::RequestContext,
    tool_handler,
};

use crate::resources;

#[derive(Clone)]
pub struct ExecutorServer {
    pub(crate) tool_router: ToolRouter<Self>,
    pub(crate) prompt_router: PromptRouter<Self>,
}

impl ExecutorServer {
    pub fn new() -> Self {
        Self {
            // `Self::tool_router()` is generated by `#[tool_router]` in tools.rs.
            tool_router: Self::tool_router(),
            // `Self::prompt_router()` is generated by `#[prompt_router]` in prompts.rs.
            prompt_router: Self::prompt_router(),
        }
    }
}

impl Default for ExecutorServer {
    fn default() -> Self {
        Self::new()
    }
}

// Pitfall 6: `#[tool_handler]` and `#[prompt_handler]` MUST share one
// `impl ServerHandler` block so the macros can co-generate `list_tools` /
// `call_tool` / `list_prompts` / `get_prompt` alongside the hand-written
// resource methods below.
#[tool_handler(router = self.tool_router)]
#[prompt_handler(router = self.prompt_router)]
impl ServerHandler for ExecutorServer {
    fn get_info(&self) -> ServerInfo {
        let caps = ServerCapabilities::builder()
            .enable_tools()
            .enable_prompts()
            .enable_resources()
            .build();
        ServerInfo::new(caps).with_instructions(
            "Onchain Strategy MCP — v1 runtime surface. \
             Write-capable tools (strategy_register, strategy_delete, strategy_run_once, \
             policy_update) return a structured `unimplemented` error (JSON-RPC code -32010, \
             data.code=\"unimplemented\", data.phase=<N>) until their phase lands. \
             Resource templates declare the strategy/execution/journal URI shapes; no objects \
             are stored in Phase 1 so `resources/read` always returns resource_not_found (-32002) \
             with data.phase=1.",
        )
    }

    async fn list_resources(
        &self,
        request: Option<PaginatedRequestParams>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, McpError> {
        resources::list_resources_impl(request, ctx).await
    }

    async fn list_resource_templates(
        &self,
        request: Option<PaginatedRequestParams>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<ListResourceTemplatesResult, McpError> {
        resources::list_resource_templates_impl(request, ctx).await
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        ctx: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResult, McpError> {
        resources::read_resource_impl(request, ctx).await
    }
}
