//! `ExecutorServer` — rmcp 1.5 `ServerHandler` owning
//! `state: Arc<tokio::sync::Mutex<StateStore>>`.
//!
//! Phase 2 change: the Phase 1 no-arg `ExecutorServer::new()` and `Default`
//! impl are REMOVED. Opening a SQLite file can fail, so the constructor is
//! `new(&StateConfig) -> anyhow::Result<Self>`. `main.rs` is updated in this
//! same plan; in-tree integration tests adopt `spawn_server_with_state`.
//!
//! Async access: `StateStore` owns a bare `rusqlite::Connection` (Sync only
//! within a single thread). All DB calls go through
//! `tokio::task::spawn_blocking` + `state.blocking_lock()` (RESEARCH Pattern 2).
//! The tokio mutex is **never** held across an `await` (Pitfall 4).

use std::sync::Arc;

use anyhow::Result;
use executor_state::StateStore;
use rmcp::{
    ErrorData as McpError, RoleServer, ServerHandler,
    handler::server::router::{prompt::PromptRouter, tool::ToolRouter},
    model::{
        GetPromptRequestParams, GetPromptResult, ListPromptsResult, ListResourceTemplatesResult,
        ListResourcesResult, PaginatedRequestParams, ReadResourceRequestParams,
        ReadResourceResult, ServerCapabilities, ServerInfo,
    },
    prompt_handler,
    service::RequestContext,
    tool_handler,
};
use tokio::sync::Mutex;

use crate::{config::StateConfig, resources};

#[derive(Clone)]
pub struct ExecutorServer {
    pub(crate) tool_router: ToolRouter<Self>,
    pub(crate) prompt_router: PromptRouter<Self>,
    pub(crate) state: Arc<Mutex<StateStore>>,
}

impl ExecutorServer {
    /// Open the SQLite store at `state_cfg.path` and assemble the server.
    /// Errors when the DB file cannot be opened/initialised.
    pub fn new(state_cfg: &StateConfig) -> Result<Self> {
        let store = StateStore::open(std::path::Path::new(&state_cfg.path))
            .map_err(|e| anyhow::anyhow!("opening state store at {}: {e}", state_cfg.path))?;
        Ok(Self {
            // `Self::tool_router()` is generated by `#[tool_router]` in tools.rs.
            tool_router: Self::tool_router(),
            // `Self::prompt_router()` is generated by `#[prompt_router]` in prompts.rs.
            prompt_router: Self::prompt_router(),
            state: Arc::new(Mutex::new(store)),
        })
    }
}

// NOTE: Phase 1's `Default for ExecutorServer` and no-arg `new()` are REMOVED.
// With Phase 2, `new` is fallible and requires a `StateConfig`; there is no
// sensible default. Every caller must pass one. Integration tests use
// `crates/executor-mcp/tests/common::spawn_server_with_state` which writes a
// throwaway config file before spawning the binary.

// Pitfall 6: `#[tool_handler]` and `#[prompt_handler]` MUST share one
// `impl ServerHandler` block so the macros can co-generate `list_tools` /
// `call_tool` / `list_prompts` / `get_prompt` alongside the hand-written
// resource methods below.
#[tool_handler(router = self.tool_router)]
#[prompt_handler(router = self.prompt_router)]
impl ServerHandler for ExecutorServer {
    fn get_info(&self) -> ServerInfo {
        let caps = ServerCapabilities::builder()
            .enable_tools()
            .enable_prompts()
            .enable_resources()
            .build();
        ServerInfo::new(caps).with_instructions(
            "Onchain Strategy MCP — Phase 2 runtime surface. \
             Strategy tools (strategy_register/list/get/delete) persist to a local \
             SQLite database. Write-capable tools pending future phases \
             (strategy_run_once → Phase 6, policy_update → Phase 5) still return \
             the structured `unimplemented` error envelope (code -32010, data.phase=<N>). \
             Storage errors use codes -32014 (not_found), -32015 (name_conflict), \
             -32016 (storage_error); validation failures use -32602 (invalid_params). \
             Resource template `strategy://{strategy_id}` now returns real objects; \
             `execution://` / `journal://` remain phase-gated.",
        )
    }

    async fn list_resources(
        &self,
        request: Option<PaginatedRequestParams>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, McpError> {
        resources::list_resources_impl(request, ctx).await
    }

    async fn list_resource_templates(
        &self,
        request: Option<PaginatedRequestParams>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<ListResourceTemplatesResult, McpError> {
        resources::list_resource_templates_impl(request, ctx).await
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        ctx: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResult, McpError> {
        // Phase 2: pass the Arc<Mutex<StateStore>> so `strategy://{id}` reads
        // the real row.
        resources::read_resource_impl(request, ctx, self.state.clone()).await
    }
}
